# Generated by Django 4.1.7 on 2023-03-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_crud", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cruding",
            fields=[
                ("c_id", models.AutoField(primary_key=True, serialize=False)),
                ("post", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
